Remove spec url form from /?doc swagger UI
wikimedia/service-template-node pull request #76
Opened 2017-02-24 22:04 UTC by ottomata

2017-02-24 22:38 UTC, Pchelolo requested changes

2017-02-24 22:38 UTC, Pchelolo commented on lib/swagger-ui.js
> +                .replace(/\s*<form id='api_selector'>[\s\S]*<\/form>/m, '');
The semicolon

2017-02-27 16:19 UTC, gwicke commented
The spec is intended to be used for various automated tools, and a precondition for being able to consume the spec is the ability to discover the URL. This patch seems to make discovering the URL significantly harder by removing all mention of it from the UI, and I'm not sure that this is something we'd want.

2017-02-27 19:38 UTC, ottomata commented
Hm, interesting.  It seems weird to use a form to let folks change the spec that a service's `/?doc` endpoint displays.  Would it make more sense to leave the form in place, but just make it uneditable?

2017-02-27 22:06 UTC, gwicke commented
@ottomata: No objections from me against making it read-only.

2017-03-06 21:00 UTC, d00rman commented
> Would it make more sense to leave the form in place, but just make it uneditable?

+1

2019-06-18 15:46 UTC, closed without merging