Update dependencies, shutdown test server properly after running tests
wikimedia/service-template-node pull request #85
Opened 2017-11-06 12:39 UTC by Pchelolo

Fixes #84 

cc @wikimedia/services

2017-11-09 12:33 UTC, d00rman requested changes
LGTM, some minor comments in package.json, otherwise :+1:

2017-11-09 12:33 UTC, d00rman commented on package.json
> +    "service-runner": "^2.4.0",
Let's bump it to 2.4.2. Also, let's bump preq to 0.5.3 once wikimedia/preq#30 is in.

2017-11-09 12:33 UTC, d00rman commented on package.json
> +  "version": "0.6.0",
I would prefer to still keep it on the 0.5.x branch, and switch to 0.6.0 once we start the switch to Node 8 in production.

2017-11-09 12:34 UTC, d00rman commented
Oh, also, let's add "8" and "node" to .travis.yml please :)

2017-11-09 13:12 UTC, Pchelolo commented
Fixed all @d00rman

2017-11-13 10:49 UTC, d00rman approved these changes

2017-11-13 10:49 UTC, merged

2017-11-13 10:52 UTC, d00rman commented
Published as [v0.5.3](https://github.com/wikimedia/service-template-node/tree/v0.5.3)